name: Tweet latest progress

on:
  schedule:
    - cron:  '0 6 * * *'
  workflow_dispatch:
  
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run script
        run: python functions.py
